################################################################################
##                        ANIMATIONS CONFIGURATION FILE                       ##
################################################################################

## Wand material
wand: BLAZE_POWDER
