name: ${project.artifactId}
main: com.ivan1pl.animations.AnimationsPlugin
version: ${project.version}
description: Animations plugin
load: POSTWORLD
softdepend: [worldedit-bukkit, bukkit, PluginUtils]
api-version: 1.16
commands:
    anim:
        description: Create or edit animation.
        usage: /anim <animation_name>
    aplay:
        description: Play animation.
        usage: /aplay <animation_name>
    alist:
        description: List animations.
        usage: /alist [page]
    adelete:
        description: Delete animation.
        usage: /adelete <animation_name>
permissions:
    animations.*:
        description: Gives access to all animations commands.
        default: op
        children:
            animations.admin: true
            animations.user: true
    animations.admin:
        description: Allows to create, remove and edit animations.
        default: op
        children:
            animations.user: true
    animations.user:
        description: Allows to play animations.
        default: op